// Type for SEO metadata (title, description, etc.)
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.scss";
import Navbar from "@/components/Navbar";
import Toast from "@/components/Toast";
// Redux Provider wrapper (client component)
import Providers from "@/store/Providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// SEO metadata for the entire app
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children, //Create a component called RootLayout that receives a read-only prop called children, which can be any React content
}: Readonly<{ 
  children: React.ReactNode; //Anything React can render
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <Providers> {/* Providers wraps all pages with Redux store, children = current page content*/}
          <Navbar />
          {children}
          <Toast />
        </Providers>
      </body>
    </html>
  );
}
